### ISSUE TITLE
Include examples on the website

### ISSUE THREAD

**Issue by dannyBies** [Augurk/public-website#8]
It would be great if a simple example showcasing Augurk's capabilities could be included on the website. Currently there are a few screenshots to look at but no interactive examples.

Having easy access to an example (+ .NET Core support!) may just convince my colleagues to start using Augurk :)

**Comment by jmezach** [comment]
@dannyBies We totally agree and we're working on that ;). We do have an interactive demo environment running at http://augurkdemo.azurewebsites.net/. We'll be sure to include a link to that from the new website as well (see #7).

As for .NET Core support, we've pretty much shipped the bits for that already in the form of [Augurk 3.0](https://github.com/Augurk/Augurk/releases). We even ship a [Docker container](https://hub.docker.com/r/augurk/augurk) now to make it super easy to get started. We're still working on some docs for that though (see #3, #6 and #5).

**Comment by dannyBies** [comment]
@jmezach Ah sweet, the demo environment is very helpful 👍.
I noticed the support for .NET Core, great work guys! 

I'll close this issue as it is already tracked in #7
